-- 063_dsb_account_roles_and_deposit_split.sql
-- ----------------------------------------------------------------------------
-- Auto-distribution of buyer deposits across a project's 4 escrow accounts.
--
-- Business rule (Saudi real-estate escrow):
--   Every buyer deposit lands on the project's GENERAL account, then is
--   automatically distributed to the 3 sub-accounts by a fixed split:
--     construction (الانشاءات)      → 76%
--     admin_marketing (اداري وتسويقي) → 20%
--     escrow (الحفظ)                → 4%
--
--   Net effect on balances:
--     general       : 100 (deposit) - 100 (offset) = 0
--     construction  : 0   +  76                    = 76
--     admin_market. : 0   +  20                    = 20
--     escrow        : 0   +   4                    = 4
--
--   Implementation: for every eligible parent payment we generate FOUR
--   derived rows (`dsb_payments.split_source_payment_id` points back to the
--   parent). ON DELETE CASCADE ties the children to the parent so re-doing
--   the split is idempotent: delete children + insert 4.
--
-- Additive + idempotent. Safe on live DB.
-- ----------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1) Account roles.
-- ---------------------------------------------------------------------------
-- Each project has at most ONE account per role. Ordinary accounts (label-
-- only, no role) stay NULL and are unaffected by distribution.
alter table dsb_project_accounts
  add column if not exists account_role text;

-- Widen or add the check constraint idempotently.
alter table dsb_project_accounts
  drop constraint if exists dsb_project_accounts_role_check;
alter table dsb_project_accounts
  add constraint dsb_project_accounts_role_check
  check (
    account_role is null
    or account_role in ('general', 'construction', 'admin_marketing', 'escrow')
  );

-- Only one account per role per project. Partial unique so unrelated NULL
-- accounts don't collide with each other.
create unique index if not exists dsb_project_accounts_role_uniq
  on dsb_project_accounts (tenant_id, project_id, account_role)
  where account_role is not null;

comment on column dsb_project_accounts.account_role is
  'One of: general | construction | admin_marketing | escrow (or NULL for ordinary accounts). Drives the auto-distribution of buyer deposits landing on the general account into the three sub-accounts.';

-- ---------------------------------------------------------------------------
-- 2) Split-tracking columns on dsb_payments.
-- ---------------------------------------------------------------------------
alter table dsb_payments
  add column if not exists split_source_payment_id uuid
    references dsb_payments(id) on delete cascade,
  add column if not exists split_percentage numeric(6,3);
--   split_percentage examples:
--     +76.000  → construction credit
--     +20.000  → admin_marketing credit
--     + 4.000  → escrow credit
--     -100.000 → offset debit on the general account (sum of the 3 above)
--   (Kept as a percentage rather than a raw amount so we can back-compute
--   the source amount for reporting: source = child.amount / (pct/100).)

create index if not exists dsb_payments_split_source_idx
  on dsb_payments (split_source_payment_id)
  where split_source_payment_id is not null;

comment on column dsb_payments.split_source_payment_id is
  'When non-null, this row was auto-generated by the buyer-deposit distribution logic. Points at the parent payment. ON DELETE CASCADE.';
comment on column dsb_payments.split_percentage is
  'The percentage used when generating this split child. +76 / +20 / +4 for the three sub-account credits; -100 for the general-account offset debit. NULL for non-split rows.';

-- ---------------------------------------------------------------------------
-- 3) Widen the deposit_category CHECK to include the derived-row category.
--    Splits get their own category so tab counts stay accurate:
--      - "تحصيل مشتري" tab keeps counting parent deposits only
--      - "توزيع تلقائي" tab surfaces the 4 derived rows per parent
--    (Migration 062 established the 5-value set; we're adding a 6th here.)
-- ---------------------------------------------------------------------------
alter table dsb_payments
  drop constraint if exists dsb_payments_deposit_category_check;
alter table dsb_payments
  add constraint dsb_payments_deposit_category_check
    check (deposit_category in (
      'buyer_collection',
      'wrong_transfer',
      'self_financing',
      'bank_financing',
      'other',
      'auto_distribution'
    ));

notify pgrst, 'reload schema';
